In [1]:
import numpy as np
import pandas as pd

## 팬시 인덱스

In [2]:
rand = np.random.RandomState(42)
x = rand.randint(100, size = 10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [3]:
ind = np.array([[1, 3],
                [2, 4]])
x[ind]

array([[92, 71],
       [14, 60]])

In [4]:
x = np.arange(12).reshape((3,4))
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
print(x[row, col])

[ 2  5 11]


In [6]:
print(row[:, np.newaxis]) # 3 x 1
x[row[:, np.newaxis], col]

[[0]
 [1]
 [2]]


array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [7]:
x = np.arange(10)
i = np.array([2, 4, 2])
x[i] = [99, 98, 87]
print(x)

[ 0  1 87  3 98  5  6  7  8  9]


In [8]:
x = np.zeros(5)
i = np.array([1, 2, 2, 3, 3, 3])
x[i] += 1
print(x)

[0. 1. 1. 1. 0.]


In [9]:
x = np.zeros(5)
i = np.array([1, 2, 2, 3, 3, 3])
np.add.at(x, i, 1)
print(x)

[0. 1. 2. 3. 0.]


## Sort

In [10]:
x = np.array([2, 1, 3, 6, 7, 5])
x_sort = np.sort(x)
x_argsort = np.argsort(x)
print(x_sort)
print(x_argsort)

[1 2 3 5 6 7]
[1 0 2 5 3 4]


In [11]:
rand = np.random.RandomState(42)
x = rand.randint(0, 10, (4, 6))
print(x,'\n')
print(np.sort(x, axis=0),'\n')
print(np.sort(x, axis=1))

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]] 

[[2 1 4 0 1 5]
 [5 2 5 4 3 7]
 [6 3 7 4 6 7]
 [7 6 7 4 9 9]] 

[[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]


In [12]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 4)

array([2, 1, 3, 4, 5, 6, 7])

## 구조화된 배열

In [13]:
name = ['a', 'b', 'c']
age = [25, 46, 37]
weight = [78.2, 97.4, 68.3]

data = np.zeros(3, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [14]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)
print(data[0]['name'])
print(data['name'][0])

[('a', 25, 78.2) ('b', 46, 97.4) ('c', 37, 68.3)]
a
a
