In [1]:
import numpy as np
import pandas as pd

# BroadCast

In [2]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
a + b

array([3, 4, 5])

In [3]:
# 장점 : [3, 3, 3]이 생성해서 수행하는 연산과 동일한 연산이 적용됨
a + 3 

array([4, 5, 6])

In [4]:
M = np.ones((3, 3))
M + a

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [5]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])[:, np.newaxis]
a + b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

### (1) a, b의 shape 변화
1   
a -> (4, 1)   
b -> (2)  

2  
a -> (4, 1)  
b -> (1, 2)  

3  
a -> (4, 2)  
b -> (4, 2)

In [6]:
a = np.array([[1], [2], [3], [4]])
b = np.array([5, 6])
c = a + b
print(a.shape, b.shape, c.shape)
print(c)

(4, 1) (2,) (4, 2)
[[ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]]


### (2) a, b의 shape 변화
1   
a -> (1 4)   
b -> (2)  

2  
a -> (1, 4)  
b -> (1, 2)  

! a + b 불가

In [7]:
a = np.array([[1, 2, 3, 4]])
b = np.array([5, 6])
print(a.shape, b.shape)

(1, 4) (2,)


### BroadCast 활용 : 표준화

In [8]:
X = np.random.random((10, 3))
X = X * np.array([10, 100, 1000])
Xmean = X.mean(0)
Xstd = X.std(0)
print(X)

[[1.50459749e+00 9.79923003e+01 5.23365645e+02]
 [9.90595032e+00 1.12380991e+00 7.10671217e+02]
 [7.62150301e+00 1.33721877e+01 9.70989462e+02]
 [3.05600773e+00 7.52503380e+01 8.15509299e+02]
 [9.70674892e+00 1.66775009e+01 6.93360123e+02]
 [3.37505519e+00 2.09281466e+01 3.30386248e+02]
 [2.51646606e+00 2.41370878e+01 7.49699049e+02]
 [5.11869662e+00 9.44321877e+01 3.17090550e+02]
 [3.56244134e-01 3.48129389e+01 9.05536393e+02]
 [6.01514099e+00 7.48275521e+01 7.16172631e+02]]


In [9]:
X_standardization = (X - Xmean) / Xstd
X_standardization

array([[-1.07692883,  1.52578263, -0.71532556],
       [ 1.57397759, -1.28213868,  0.17842605],
       [ 0.85315844, -0.92709567,  1.42056661],
       [-0.58740727,  0.86656269,  0.67867387],
       [ 1.51112292, -0.83128474,  0.09582403],
       [-0.48673718, -0.70807152, -1.63615051],
       [-0.75765062, -0.61505413,  0.36465215],
       [ 0.06343972,  1.42258585, -1.69959258],
       [-1.43927254, -0.30559385,  1.10824923],
       [ 0.34629776,  0.85430742,  0.20467672]])

# 비교, 마스크, 부울 로직

In [10]:
x = np.array([1, 2, 3, 4, 5])
x > 3

array([False, False, False,  True,  True])

In [11]:
x = np.array([1, 2, 3, 4, 5])
print(np.count_nonzero(x > 3)) # True인 조건 개수 확인 1 
print(np.sum(x > 3)) # True인 조건 개수 확인 2

2
2


In [12]:
x = np.array([1, 2, 3, 4, 5])
x[x < 4]

array([1, 2, 3])

In [13]:
a = np.array([True, False, True, False, True, False])
b = np.array([False, True, False, True, False, True])

In [14]:
a | b

array([ True,  True,  True,  True,  True,  True])

In [15]:
a or b

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()