In [2]:
import numpy as np
import pandas as pd

# 파이썬의 loop가 느린 이유

- 파이썬은 동적인 인터프리터 언어이기 때문임
- 타입을 알 수 없기 때문에 계산 시 확인 후 연산이 이루어짐.(컴파일 과정에서 최적화가 제한됨)

In [3]:
def slow(data_lst):
    result_lst = []
    for data in data_lst:
        result_lst.append(data*-1)
    return np.array(result_lst)

In [4]:
data_lst = np.random.randint(1,10, size=5)
%timeit slow(data_lst)

2.59 µs ± 67.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Ufuncs : 유니버설 함수
리스트에 바로 적용할 수 있는 함수들
- 산술 연산 모두 사용 가능 ( +, -, *, /, %, **)
- 절대값 함수 : abs()
- 삼각 함수 : np.sin(), np.cos(), np.tan(), np.arcsin(), np.arccos(), np.arctan()
- 지수 함수 : np.exp(), np.exp2(), np.power(), np.expm1()
- 로그 함수 : np.log(), np.log2(), np.log10(), np.log1p()

In [23]:
print(slow(data_lst))
print(data_lst*-1)

%timeit data_lst*-1

[-6 -8 -1 -4 -9]
[-6 -8 -1 -4 -9]
727 ns ± 37.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [26]:
# 두 벡터의 길이가 맞으면 아래처럼 연산도 가능
# 동일한 위치의 원소끼리 연산된 array return
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [34]:
x = np.arange(4).reshape((2,2))
print(x)
print(x**2) # 각 원소 제곱
print(2**x) # 원소 각각을 2^n

[[0 1]
 [2 3]]
[[0 1]
 [4 9]]
[[1 2]
 [4 8]]


In [18]:
# 고급 기능 : out 사용 시 메모리 소모를 줄일 수 있음
x = np.arange(5)
y = np.empty(5)
# x*10 == np.multiply(x, 10) 
np.multiply(x, 10, out=y)
print(x)
print(y)

[0 1 2 3 4]
[ 0. 10. 20. 30. 40.]


In [45]:
# 고급 기능 : out 사용 시 메모리 소모를 줄일 수 있음
y = np.zeros(10)
np.power(2, x, out=y[::2]) # vs. y[::2] = 2 ** x
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [35]:
# 고급 기능 : reduce()
x = np.arange(1, 5)
print(x)
print(np.add.reduce(x))
print(np.multiply.reduce(x))

[1 2 3 4]
10
24


In [34]:
# 고급기능 : accumulate()
x = np.arange(1, 5)
print(x)
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))

[1 2 3 4]
[ 1  3  6 10]
[ 1  2  6 24]


In [61]:
# Outer products
x = np.arange(1,6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

# 집계함수
- sum() vs np.sum()
- min() vs np.min()
- max() vs np.max()

## 기타 집계함수
- np.prod()
- np.mean()
- np.std()
- np.var()
- np.argmin()
- np.argmax()
- np.median()
- np.any()
- np.all()